modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="endermiteprotection"
version="1.0.0"
displayName="Enderman Tower Bait Protection"
description="Prevents L2 Hostility Killer Aura damage to the tagged endermite bait."
authors="Misaka24"

[[dependencies.endermiteprotection]]
modId="neoforge"
type="required"
versionRange="[47.1.106,)"
ordering="NONE"
side="BOTH"

[[dependencies.endermiteprotection]]
modId="minecraft"
type="required"
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"

[[dependencies.endermiteprotection]]
modId="l2hostility"
type="required"
versionRange="[2.5.19,)"
ordering="AFTER"
side="BOTH"
